version: '3.8'

services:
  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: brik_backend_prod
    environment:
      NODE_ENV: ${NODE_ENV}
      PORT: ${PORT}
      JWT_SECRET: ${JWT_SECRET}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "127.0.0.1:3001:3000"
    depends_on:
      - postgres
    networks:
      - nginx-proxy_network
    restart: unless-stopped
    env_file:
      - .env

  # Frontend with SSL support
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: brik_frontend_prod
    ports:
      - "8080:80"    # Different HTTP port
      - "8443:443"   # Different HTTPS port
    depends_on:
      - backend
    networks:
      - nginx-proxy_network
    restart: unless-stopped
    volumes:
      - ./nginx/ssl:/etc/nginx/ssl:ro  # Mount SSL certificates

volumes:
  postgres_data_prod:

networks:
  nginx-proxy_network:
    name: nginx-proxy_network
    external: true