version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: brik_postgres_prod
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5433:5432"  # Different port to avoid conflicts
    networks:
      - brik-network
    restart: unless-stopped
    env_file:
      - .env

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: brik_backend_prod
    environment:
      NODE_ENV: ${NODE_ENV}
      PORT: ${PORT}
      JWT_SECRET: ${JWT_SECRET}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${POSTGRES_DB}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "127.0.0.1:3001:3000"
    depends_on:
      - postgres
    networks:
      - brik-network
    restart: unless-stopped
    env_file:
      - .env

  # Frontend with SSL support
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: brik_frontend_prod
    ports:
      - "8080:80"    # Different HTTP port
      - "8443:443"   # Different HTTPS port
    depends_on:
      - backend
    networks:
      - brik-network
    restart: unless-stopped
    volumes:
      - ./nginx/ssl:/etc/nginx/ssl:ro  # Mount SSL certificates

volumes:
  postgres_data_prod:

networks:
  brik-network:
    driver: bridge